greeting-app:
  chartName: greeting-app
  deployment: 
    replicaCount: 1
    image: 3d-testkube-registry:6000/greeter:latest
    tag: 37c9543
  config:
    port: 8000 #should be the same as deployment port
    greeting: Bonjour
  ingress:
    rule: PathPrefix(`/prod`)
