greeting-app:
  chartName: greeting-app
  deployment: 
    replicaCount: 1
    image: k3d-testkube-registry:6000/greeter:latest
    tag: 7b0245f
  config:
    port: 8000
    greeting: Hello
  ingress:
    rule: PathPrefix(`/stage`)
