greeting-app:
  chartName: greeting-app
  deployment: 
    replicaCount: 1
    image: ghcr.io/rallinator7/greeter-app
    tag: 7b0245f
  config:
    port: 8000
    greeting: Hello
  ingress:
    rule: PathPrefix(`/stage`)